<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-01-12T03:01:46Z" name="Suite" finished-at="2022-01-12T03:03:13Z" duration-ms="86721">
    <groups>
    </groups>
    <test started-at="2022-01-12T03:01:46Z" name="Test3" finished-at="2022-01-12T03:03:12Z" duration-ms="86087">
      <class name="extentReportGeneration.ExtentReportDemo3">
        <test-method is-config="true" signature="startApp()[pri:0, instance:extentReportGeneration.ExtentReportDemo3@495b0487]" started-at="2022-01-12T08:31:46Z" name="startApp" finished-at="2022-01-12T08:32:24Z" duration-ms="37561" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="validateTitle()[pri:0, instance:extentReportGeneration.ExtentReportDemo3@495b0487]" started-at="2022-01-12T08:32:24Z" name="validateTitle" finished-at="2022-01-12T08:32:44Z" duration-ms="20148" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method signature="validateTitle123()[pri:0, instance:extentReportGeneration.ExtentReportDemo3@495b0487]" started-at="2022-01-12T08:32:44Z" name="validateTitle123" finished-at="2022-01-12T08:32:46Z" duration-ms="1705" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Webnetram-Login] but found [Webnetram-Login23]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Webnetram-Login] but found [Webnetram-Login23]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at extentReportGeneration.ExtentReportDemo3.validateTitle123(ExtentReportDemo3.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle123 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:extentReportGeneration.ExtentReportDemo3@495b0487]" started-at="2022-01-12T08:32:46Z" name="tearDown" finished-at="2022-01-12T08:33:12Z" duration-ms="26660" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReportGeneration.ExtentReportDemo3 -->
    </test> <!-- Test3 -->
    <test started-at="2022-01-12T03:01:46Z" name="Test1" finished-at="2022-01-12T03:03:13Z" duration-ms="86721">
      <class name="extentReportGeneration.ExtentReportDemo">
        <test-method is-config="true" signature="startApp()[pri:0, instance:extentReportGeneration.ExtentReportDemo@487db668]" started-at="2022-01-12T08:31:46Z" name="startApp" finished-at="2022-01-12T08:32:19Z" duration-ms="32778" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="validateTitle()[pri:0, instance:extentReportGeneration.ExtentReportDemo@487db668]" started-at="2022-01-12T08:32:20Z" name="validateTitle" finished-at="2022-01-12T08:32:42Z" duration-ms="21906" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method signature="validateTitle123()[pri:0, instance:extentReportGeneration.ExtentReportDemo@487db668]" started-at="2022-01-12T08:32:42Z" name="validateTitle123" finished-at="2022-01-12T08:32:52Z" duration-ms="10211" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Webnetram-Login] but found [Webnetram-Login23]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Webnetram-Login] but found [Webnetram-Login23]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at extentReportGeneration.ExtentReportDemo.validateTitle123(ExtentReportDemo.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle123 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:extentReportGeneration.ExtentReportDemo@487db668]" started-at="2022-01-12T08:32:52Z" name="tearDown" finished-at="2022-01-12T08:33:13Z" duration-ms="21348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReportGeneration.ExtentReportDemo -->
    </test> <!-- Test1 -->
    <test started-at="2022-01-12T03:01:46Z" name="Test2" finished-at="2022-01-12T03:03:12Z" duration-ms="86087">
      <class name="extentReportGeneration.ExtentReportDemo2">
        <test-method is-config="true" signature="startApp()[pri:0, instance:extentReportGeneration.ExtentReportDemo2@6bbe2511]" started-at="2022-01-12T08:31:46Z" name="startApp" finished-at="2022-01-12T08:32:19Z" duration-ms="32777" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="validateTitle()[pri:0, instance:extentReportGeneration.ExtentReportDemo2@6bbe2511]" started-at="2022-01-12T08:32:20Z" name="validateTitle" finished-at="2022-01-12T08:32:43Z" duration-ms="23301" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method signature="validateTitle123()[pri:0, instance:extentReportGeneration.ExtentReportDemo2@6bbe2511]" started-at="2022-01-12T08:32:43Z" name="validateTitle123" finished-at="2022-01-12T08:32:46Z" duration-ms="2929" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Webnetram-Login] but found [Webnetram-Login23]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Webnetram-Login] but found [Webnetram-Login23]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at extentReportGeneration.ExtentReportDemo2.validateTitle123(ExtentReportDemo2.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle123 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:extentReportGeneration.ExtentReportDemo2@6bbe2511]" started-at="2022-01-12T08:32:46Z" name="tearDown" finished-at="2022-01-12T08:33:12Z" duration-ms="26603" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReportGeneration.ExtentReportDemo2 -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
