<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-01-12T06:57:34Z" name="Suite" finished-at="2022-01-12T06:57:53Z" duration-ms="18670">
    <groups>
    </groups>
    <test started-at="2022-01-12T06:57:34Z" name="Test1" finished-at="2022-01-12T06:57:46Z" duration-ms="11796">
      <class name="extentReportWithScreenShot.ExtentReportDemo">
        <test-method is-config="true" signature="startApp()[pri:0, instance:extentReportWithScreenShot.ExtentReportDemo@1afdd473]" started-at="2022-01-12T12:27:34Z" name="startApp" finished-at="2022-01-12T12:27:41Z" duration-ms="6796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="validateTitle1()[pri:0, instance:extentReportWithScreenShot.ExtentReportDemo@1afdd473]" started-at="2022-01-12T12:27:41Z" name="validateTitle1" finished-at="2022-01-12T12:27:45Z" duration-ms="3937" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle1 -->
        <test-method signature="validateTitle2()[pri:0, instance:extentReportWithScreenShot.ExtentReportDemo@1afdd473]" started-at="2022-01-12T12:27:45Z" name="validateTitle2" finished-at="2022-01-12T12:27:45Z" duration-ms="550" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Webnetram-Login] but found [Webnetram-Login23]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Webnetram-Login] but found [Webnetram-Login23]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at extentReportWithScreenShot.ExtentReportDemo.validateTitle2(ExtentReportDemo.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:extentReportWithScreenShot.ExtentReportDemo@1afdd473]" started-at="2022-01-12T12:27:46Z" name="tearDown" finished-at="2022-01-12T12:27:46Z" duration-ms="150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReportWithScreenShot.ExtentReportDemo -->
    </test> <!-- Test1 -->
    <test started-at="2022-01-12T06:57:34Z" name="Test2" finished-at="2022-01-12T06:57:48Z" duration-ms="13590">
      <class name="extentReportWithScreenShot.ExtentReportDemo2">
        <test-method is-config="true" signature="startApp()[pri:0, instance:extentReportWithScreenShot.ExtentReportDemo2@38831718]" started-at="2022-01-12T12:27:34Z" name="startApp" finished-at="2022-01-12T12:27:41Z" duration-ms="6786" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="validateTitle3()[pri:0, instance:extentReportWithScreenShot.ExtentReportDemo2@38831718]" started-at="2022-01-12T12:27:41Z" name="validateTitle3" finished-at="2022-01-12T12:27:47Z" duration-ms="5833" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle3 -->
        <test-method signature="validateTitle4()[pri:0, instance:extentReportWithScreenShot.ExtentReportDemo2@38831718]" started-at="2022-01-12T12:27:47Z" name="validateTitle4" finished-at="2022-01-12T12:27:47Z" duration-ms="578" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Webnetram-Login] but found [Webnetram-Login23]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Webnetram-Login] but found [Webnetram-Login23]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at extentReportWithScreenShot.ExtentReportDemo2.validateTitle4(ExtentReportDemo2.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle4 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:extentReportWithScreenShot.ExtentReportDemo2@38831718]" started-at="2022-01-12T12:27:47Z" name="tearDown" finished-at="2022-01-12T12:27:48Z" duration-ms="99" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReportWithScreenShot.ExtentReportDemo2 -->
    </test> <!-- Test2 -->
    <test started-at="2022-01-12T06:57:34Z" name="Test3" finished-at="2022-01-12T06:57:53Z" duration-ms="18670">
      <class name="extentReportGeneration.ExtentReportDemo3">
        <test-method is-config="true" signature="startApp()[pri:0, instance:extentReportGeneration.ExtentReportDemo3@5adb0db3]" started-at="2022-01-12T12:27:34Z" name="startApp" finished-at="2022-01-12T12:27:40Z" duration-ms="6440" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="validateTitle7()[pri:0, instance:extentReportGeneration.ExtentReportDemo3@5adb0db3]" started-at="2022-01-12T12:27:40Z" name="validateTitle7" finished-at="2022-01-12T12:27:52Z" duration-ms="11238" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Webnetram-Login] but found [Webnetram-Login23]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Webnetram-Login] but found [Webnetram-Login23]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at extentReportGeneration.ExtentReportDemo3.validateTitle7(ExtentReportDemo3.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle7 -->
        <test-method signature="validateTitle8()[pri:0, instance:extentReportGeneration.ExtentReportDemo3@5adb0db3]" started-at="2022-01-12T12:27:52Z" name="validateTitle8" finished-at="2022-01-12T12:27:53Z" duration-ms="481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle8 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:extentReportGeneration.ExtentReportDemo3@5adb0db3]" started-at="2022-01-12T12:27:53Z" name="tearDown" finished-at="2022-01-12T12:27:53Z" duration-ms="90" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReportGeneration.ExtentReportDemo3 -->
    </test> <!-- Test3 -->
  </suite> <!-- Suite -->
</testng-results>
